services:
  cyber-audit-backend:
    image: ghcr.io/alsewedy/cyber-audit-portal:${IMAGE_TAG:-latest}
    container_name: cyber-audit-backend
    command: node backend-api.js
    ports:
      - "3050:3050"
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  cyber-audit-frontend:
    image: ghcr.io/alsewedy/cyber-audit-portal:${IMAGE_TAG:-latest}
    container_name: cyber-audit-frontend
    command: node server.js
    ports:
      - "4500:4500"
    depends_on:
      - cyber-audit-backend
    restart: unless-stopped
